### PR TITLE
Topic/pmixstat

### PR DESCRIPTION
**Pull request by jjhursey**
CI testing for upstream: https://github.com/open-mpi/ompi/pull/7202

### CODE REVIEW

**Comment by ibm-ompi** [comment]
The IBM CI (GNU/Scale) build failed! Please review the log, linked below.

 Gist: https://gist.github.com/f80e5bdffc4738ddcf704c0114e780b6

**Comment by ibm-ompi** [comment]
The IBM CI (XL) build failed! Please review the log, linked below.

 Gist: https://gist.github.com/0c6e44147f05d5343ae6ab34c2609bcb

**Comment by jjhursey** [comment]
bot:ibm:retest

**Comment by ibm-ompi** [comment]
The IBM CI (GNU/Scale) build failed! Please review the log, linked below.

 Gist: https://gist.github.com/ibm-ompi/88b480fb98dfd2bdac939f023e1f8fe6

**Comment by jjhursey** [comment]
bot:ibm:gnu:retest
bot:ibm:nodes:3:test

**Comment by ibm-ompi** [comment]
The IBM CI (XL) build failed! Please review the log, linked below.

 Gist: https://gist.github.com/d88abb002df75079a19cf59de7c9241b

**Comment by jjhursey** [comment]
bot:ibm:prrte:retest

**Comment by ibm-ompi** [comment]
The IBM CI (GNU/Scale) build failed! Please review the log, linked below.

 Gist: https://gist.github.com/ibm-ompi/88b480fb98dfd2bdac939f023e1f8fe6

**Comment by jjhursey** [comment]
bot:ibm:prrte:retest

**Comment by jjhursey** [comment]
bot:ibm:xl:retest

**Comment by jjhursey** [comment]
bot:ibm:prrte:retest

**Comment by jjhursey** [comment]
bot:ibm:prrte:retest

**Comment by jjhursey** [comment]
bot:ibm:retest

**Comment by jjhursey** [comment]
bot:ibm:retest

**Comment by jjhursey** [comment]
bot:ibm:retest

**Comment by ibm-ompi** [comment]
The IBM CI (PRRTE) build failed! Please review the log, linked below.

 Gist: https://gist.github.com/19d84ead9473d35fd7343b6c24ff8bfa

**Comment by jjhursey** [comment]
bot:ibm:retest

**Comment by ibm-ompi** [comment]
The IBM CI (PRRTE) build failed! Please review the log, linked below.

 Gist: https://gist.github.com/0bc63ee355523e9b3b0f6dcc39d8dffd

**Comment by jjhursey** [comment]
bot:ibm:retest

**Comment by ibm-ompi** [comment]
The IBM CI (PRRTE) build failed! Please review the log, linked below.

 Gist: https://gist.github.com/47664cf5630ac7307abaca1c4e822de3

**Comment by jjhursey** [comment]
bot:ibm:retest

**Comment by jjhursey** [comment]
bot:ibm:retest

**Comment by jjhursey** [comment]
bot:ibm:pgi:retest

**Pull request closed without merging**
